version: '2'

services:
  website:
    image: tiangolo/uwsgi-nginx-flask:python3.6
    volumes:
      - ./app:/app
    ports:
      - 80:80
    env_file:
      - env.env

  docker_api:
    image: tiangolo/uwsgi-nginx-flask:python3.6
    volumes:
      - ./api:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
    environment:
      - HOSTNAME = 127.0.0.1
    env_file:
      - env.env
